### ISSUE TITLE
push latest chocolatey release to supermarket with windows cookbook dependancy loosened up

### ISSUE THREAD

**Issue by Stromweld** [chocolatey/chocolatey-cookbook#104]
I'm currently running latest chef-client 12.13.37 and rely on windows 2.0.2 cookbook. Due to this berks is installing chocolatey 0.1.0 due to all other versions wanting windows cookbook below 2.0. The fix has already been merged to master but not pushed out to supermarket.

**Comment by mwrock** [comment]
I'll get this released very very soon @Stromweld

**Comment by mwrock** [comment]
Its on supermarket now: https://supermarket.chef.io/cookbooks/chocolatey

**Comment by Stromweld** [comment]
sweet thanks
