### ISSUE TITLE
Increase timeout?

### ISSUE THREAD

**Issue by joemillerr** [chocolatey/chocolatey-cookbook#107]
Hello,

I'm trying to install Visual Studio which takes quite a long time and chocolatey keeps timing out.  It looks like the timeout is set to 900 seconds when Chef fails but Chocolatey's default (according to the official documentation) is 2700 seconds.  Somewhere the timeout is being adjusted to 900 but I can't find anything in the cookbook that is doing that.

**Comment by ferventcoder** [comment]
Cookbook or built-in Chef Chocolatey resource?

**Comment by joemillerr** [comment]
@ferventcoder ah crap you are totally right.  I forgot "chocolatey_package" is a built in resource now. Closing

**Comment by ferventcoder** [comment]
Second question - is this a timeout downloading or installing?

Note the following from https://chocolatey.org/docs/commands-install :

~~~sh
    --timeout, --execution-timeout=VALUE
     CommandExecutionTimeout (in seconds) - The time to allow a command to 
       finish before timing out. Overrides the default execution timeout in the 
       configuration of 2700 seconds.
~~~

However it doesn't cover web request timeouts, although I don't think that applies here.

~~~sh
> choco config list
webRequestTimeoutSeconds = 30 | Default timeout for web requests. Available in 0.9.10+.
~~~

**Comment by joemillerr** [comment]
@ferventcoder it happens during installation so I believe it applies in this case.

**Comment by ferventcoder** [comment]
Unknown what is causing it to time out at 900 seconds, unless it is something built into Chef or the chocolatey_package resource.

**Comment by ferventcoder** [comment]
And yes, the execution timeout would apply, not the web request timeout.

**Comment by mwrock** [comment]
Hey sorry for taking so long to get back here. The 900 second timeout comes from the base package resource which is the default timeout for package installs. You can increase this by adding a `timeout` property to your `chocolatey_package` and making it a value sufficiently long for your install.
