### ISSUE TITLE
Overlap between chocolatey-cookbook and Chef chocolatey resource?

### ISSUE THREAD

**Issue by donbecker** [chocolatey/chocolatey-cookbook#110]
Apologies if I'm a noob and missed something. 

This cookbook states that it can manage Chocolatey packages. 

However there is also the "chocolatey_package" resource: [https://docs.chef.io/resource_chocolatey_package.html](url)

What's a Chef Chocolatey user to do?

**Comment by ferventcoder** [comment]
Use the built-in resource `chocolatey_package` - use this cookbook only to manage the installation of Chocolatey itself. HTH

**Comment by donbecker** [comment]
Thanks!
