### ISSUE TITLE
Bring Install.ps1 ERB up to date 

### ISSUE THREAD

**Issue by ferventcoder** [chocolatey/chocolatey-cookbook#112]
Here is a similar install.p1 that has been kept up to date to allow great compatibility - https://github.com/puppetlabs/puppetlabs-chocolatey/blob/master/templates/InstallChocolatey.ps1.erb

- [ ] has TLS 1.1/1.2 fixes (done with #111)
- [ ] Fix PowerShell Output Redirect Bug in PowerShell v2/3
- [ ] Allow switching out 7zip for built-in compression to remove the download from the internet
- [ ] Fix any other formatting
 
cc @mwrock @docwhat

**Comment by ferventcoder** [comment]
Related to reviewing changes for #109 in #111.

**Comment by docwhat** [comment]
Also see #113 as an alternative that uses the official version.

**Comment by docwhat** [comment]
Another alternative would be to just use the official version... drop it in `files/` and use `cookbook_file`.  Then updating it would be as easy as grabbing the latest and dropping it in.
