### ISSUE TITLE
Make 7zip download location a configurable option

### ISSUE THREAD

**Issue by bender-the-greatest** [chocolatey/chocolatey-cookbook#124]
As it stands, even if you specify an alternate download location for the Chocolatey nupkg, the recipe still tries to download https://chocolatey.org/7za.exe. This causes issues for installing chocolatey on systems with no access to the internet, even if you have the nupkg available on an internal network with your own internal package sources.

It would be desirable to be able to configure the URL of 7za.exe, or even to specify to use the system installed version of 7zip instead of assuming that chocolatey.org is accessible.

**Comment by metalseargolid** [comment]
Started looking into this as I was planning on making a PR for this issue, but found out that there is the chocolateyUseWindowsCompression envvar to bypass the 7zip requirement. Would be nice if this were configurable as a cookbook attribute (looks like it's defined but not in use).

**Comment by ferventcoder** [comment]
@metalseargolid I believe you can do so but would lean on @mwrock for his knowledge on that.

**Comment by mwrock** [comment]
yes. I would gladly accept a PR that passes that via an attribute!
