### ISSUE TITLE
NoMethodError: undefined method `args' for Chef::Resource::ChocolateyPackage

### ISSUE THREAD

**Issue by nicutor** [chocolatey/chocolatey-cookbook#129]
### Cookbook version
[Version of the cookbook where you are encountering the issue]
1.2.1

### Chef-client version
[Version of chef-client in your environment]
13.2.20

### Platform Details
[Operating system distribution and release version. Cloud provider if running in the cloud]
Windows 7 SP1 with latest updates
chefdk 2.0.28
PowerShell 5.1
Microsoft Visual C++ 2010 x64 and x86

### Scenario:
[What you are trying to achieve and you can't?]
Trying to pass some arguments for installing a package.

### Steps to Reproduce:
[If you are filing an issue what are the things we need to do in order to repro your problem? How are you using this cookbook or any resources it includes?]
```
chocolatey_package 'docker-toolbox' do
  args '/COMPONENTS="docker,dockermachine,dockercompose,kitematic"'
end
```

### Expected Result:
[What are you expecting to happen as the consequence of above reproduction steps?]
To pass the args to installer

### Actual Result:
[What actually happens after the reproduction steps? Include the error output or a link to a gist if possible.]
```
NoMethodError
-------------
undefined method `args' for Chef::Resource::ChocolateyPackage

System Info:
------------
chef_version=13.2.20
platform=windows
platform_version=6.1.7601
ruby=ruby 2.4.1p111 (2017-03-22 revision 58053) [i386-mingw32]
program_name=C:/opscode/chefdk/modules/chef/../../bin/chef-client
executable=C:/opscode/chefdk/bin/chef-client
```

Can somebody dig this and fix it?

The same thing is happening when I use:
```
chocolatey 'docker-toolbox' do
  args '/COMPONENTS="docker,dockermachine,dockercompose,kitematic"'
end
```
The result is:
```
    ================================================================================
    Error executing action `install` on resource 'chocolatey[docker-toolbox]'
    ================================================================================

    NoMethodError
    -------------
    undefined method `new' for Chocolatey:Module

    chocolatey("docker-toolbox") do
      action [:install]
      default_guard_interpreter :default
      declared_type :chocolatey
      cookbook_name "cookbook_name"
      recipe_name "docker"
      args "/COMPONENTS=\"docker,dockermachine,dockercompose,kitematic\""
      package "docker-toolbox"
    end

    System Info:
    ------------
    chef_version=13.2.20
    platform=windows
    platform_version=6.1.7601
    ruby=ruby 2.4.1p111 (2017-03-22 revision 58053) [i386-mingw32]
    program_name=C:/opscode/chefdk/modules/chef/../../bin/chef-client
    executable=C:/opscode/chefdk/bin/chef-client
```

**Comment by mwrock** [comment]
On chef 13, you want to use the chocolatey_package resource and use it's options property. It does not have an args property. See https://docs.chef.io/resource_chocolatey_package.html for it's documentation.
