### ISSUE TITLE
Add Matt Wrock as a collaborator

### ISSUE THREAD

**Issue by ferventcoder** [chocolatey/chocolatey-cookbook#27]
@guilhem can we add @mwrock as a collaborator on the supermarket?

**Comment by AnneTheAgile** [comment]
@ferventcoder , I think you mean on the chef site, right? https://supermarket.chef.io/cookbooks/chocolatey

**Comment by ferventcoder** [comment]
That's why I said supermarket in the description.

**Comment by AnneTheAgile** [comment]
@ferventcoder , yes that's what I thought, but if so then I'm confused why @guilhem was expecting commits here? Am I off base?
AnneTheAgile, codeTriage fan

**Comment by dougireton** [comment]
Bumping this thread. I'd love to see a new release of this cookbook on Supermarket. I'm dependent on the changes on master to allow installing behind a proxy.

**Comment by mwrock** [comment]
I have been added. Thanks @guilhem !
