### ISSUE TITLE
Not working with Chocolatey >= 0.9.9

### ISSUE THREAD

**Issue by rusitschka** [chocolatey/chocolatey-cookbook#34]
This cookbook doesn't work with version 0.9.9 and above. The main reason is the missing "-y" flag.

**Comment by rusitschka** [comment]
I forked to https://github.com/rusitschka/chocolatey-cookbook and added some support for 0.9.9. Most of it is not tested, yet => No pull request, yet.

**Comment by ferventcoder** [comment]
Similar work for the Puppet provider being done over here: https://github.com/chocolatey/puppet-chocolatey/pull/49

**Comment by MattHodge** [comment]
Running the cookbook twice works, just errors the first time.

**Comment by pplante** [comment]
Can we get this resolved? It makes Chef via CI very difficult/annoying.

**Comment by ferventcoder** [comment]
#35 implements this. @guilhem @mwrock ping

**Comment by cmluciano** [comment]
This can probably be closed

**Comment by mwrock** [comment]
Closing. We recently bumped to the latest version of this cookbook and removed the `node.default['chocolatey']['upgrade']=false` and no longer have issues with v9.9.x.
