### ISSUE TITLE
`choco list` will become local only

### ISSUE THREAD

**Issue by alexchandel** [chocolatey/chocolatey-cookbook#44]
Per [choco#158](https://github.com/chocolatey/choco/issues/158), `choco list` may default to local only in the future. `choco search` should be used instead to list all packages, including those not installed.

**Comment by ferventcoder** [comment]
I fail to understand the purpose of this issue - https://github.com/chocolatey/chocolatey-cookbook/blob/master/providers/default.rb#L87 is where this is used and it wants to know ONLY about locally installed packages. Same with the puppet provider.

**Comment by ferventcoder** [comment]
Closing as invalid.

**Comment by alexchandel** [comment]
Sorry, overly broad search parameters!
