### ISSUE TITLE
ChefSpec matchers missing.

### ISSUE THREAD

**Issue by rodrigdav** [chocolatey/chocolatey-cookbook#49]
Could we get some Chefspec matchers added to this cookbook.  I am using the chocolatey resource in a recipe and would like to use ChefSpec to do unit testing.  I can do a PR to add it if that would help.

**Comment by mwrock** [comment]
I think such a PR would be most welcome! :+1:

**Comment by rodrigdav** [comment]
Alright I can do that.  Sorry about the delay here.

**Comment by rodrigdav** [comment]
Alright I have this but I can't seem to be able to push my branch to make a pr.  Thoughts?

**Comment by mwrock** [comment]
did you fork a repo under your own account? Or did you create a branch under this repo? I'm guesssing you did the latter but you need to do the former.

**Comment by rodrigdav** [comment]
Here is the pull request.   https://github.com/chocolatey/chocolatey-cookbook/pull/58

**Comment by dougireton** [comment]
This was implemented in PR https://github.com/chocolatey/chocolatey-cookbook/pull/63, which is now merged. This issue can be closed as fixed.
