### ISSUE TITLE
Missing v0.4.0 tag

### ISSUE THREAD

**Issue by anastasds** [chocolatey/chocolatey-cookbook#50]
There is a v0.4.0 of this cookbook available on Chef SuperMarket:

https://supermarket.chef.io/cookbooks/chocolatey

However, there is no v0.4.0 listed for this repo.

**Comment by kamaradclimber** [comment]
same for v0.4.1 tag. I have some automatic tools relying on tag presence, could you push them ?

thanks

**Comment by mwrock** [comment]
My apologies. I neglected to push those upstream. Just pushed them now.
