### ISSUE TITLE
Problems with 0.5.0 version

### ISSUE THREAD

**Issue by EYurchenko** [chocolatey/chocolatey-cookbook#64]
Compiling Cookbooks...

================================================================================
Recipe Compile Error in /home/eyurchenko/.chef/cache/cookbooks/chocolatey/providers/default.rb
================================================================================

NameError
---------
uninitialized constant Chef::Provider::Chocolatey::Helpers

Cookbook Trace:
---------------
  /home/eyurchenko/.chef/cache/cookbooks/chocolatey/providers/default.rb:19:in `class_from_file'

Relevant File Content:
----------------------
/home/eyurchenko/.chef/cache/cookbooks/chocolatey/providers/default.rb:

 12:  #
 13:  # Unless required by applicable law or agreed to in writing, software
 14:  # distributed under the License is distributed on an "AS IS" BASIS,
 15:  # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 16:  # See the License for the specific language governing permissions and
 17:  # limitations under the License.
 18:  #
 19>> include Chocolatey::Helpers
 20:
 21:  use_inline_resources
 22:
 23:  # Support whyrun
 24:  def whyrun_supported?
 25:    true
 26:  end
 27:
 28:  def load_current_resource # rubocop:disable Metrics/AbcSize

Running handlers:
[2015-11-10T13:57:00+00:00] ERROR: Running exception handlers
Running handlers complete
[2015-11-10T13:57:00+00:00] ERROR: Exception handlers complete
[2015-11-10T13:57:00+00:00] FATAL: Stacktrace dumped to /home/eyurchenko/.chef/cache/chef-stacktrace.out
Chef Client failed. 0 resources updated in 4.623317211 seconds
[2015-11-10T13:57:00+00:00] ERROR: uninitialized constant Chef::Provider::Chocolatey::Helpers
[2015-11-10T13:57:00+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)

There is no such problem with 0.4.1

**Comment by mwrock** [comment]
Thanks for reporting this. What version of chef are you using?

**Comment by EYurchenko** [comment]
$ chef-client --version
Chef: 12.3.0

**Comment by mwrock** [comment]
Thanks. I am able to reproduce on 12.3.0 (works on latest 12.5.1). Will get a fix up shortly.

**Comment by mwrock** [comment]
My apologies for the break and thanks again for reporting. I have a fix and will merge/release 0.5.1 as soon as the PR goes green.

**Comment by EYurchenko** [comment]
No problem. Fixed version works fine. Thanks for fixing that fast!
