### ISSUE TITLE
Packages that change the path cannot be in same run as packages that depend on them

### ISSUE THREAD

**Issue by byrney** [chocolatey/chocolatey-cookbook#67]
I recently tried changing my vagrant provisioning from using shell and chocolatey to using chef. I ran into a number of problems that were very tricky to track down

```ruby
chocolatey 'git.install' do
    options 'params' => "'/GitOnlyOnPath'"
end

git 'Users/IEUser/Config' do
    repository 'https://github.com/byrney/Config.git'
end
```

The git clone will fail because git is added to the user path but the chef process does not pick up the changes. A workaround is to explicitly add git to the path in the recipe using a ruby_block or to split into two chef runs (install git, use git).

The second one is worse since it stomped all over my chef install

```ruby
chocolatey 'ruby' do
    action :install
    version '2.1.6'
end

chocolatey 'rubygems' do
    action :install
    version '2.4.6'
end
```

`ruby` gets installed and adds itself to the path. `rubygems` assumes that the system ruby is first on the path and does this:

```powershell
Start-ChocolateyProcessAsAdmin 'setup.rb' 'ruby' -validExitCodes $validExitCodes
```

The ruby just installed is not on the path and the `rubygems` package will "upgrade" the gems in `c:\opscode\chef\embedded\...` which is the only ruby in the path at this point.

My workaround of adding the chocolatey ruby to `ENV['PATH']` in the recipe worked until ruby got updated (the chocolatey ruby directory includes the version number) and then the gems package stomped on the opscode version again.

There seems to be specific logic in `ruby2.devkit` package to handle this, refreshing the local `$env:PATH` before calling ruby. Adding it to the `rubygems` package would fix the problem but wouldn't fix the issue with the git cookbook.

I created a fork of the chocolatey cookbook which will refresh `ENV['PATH']` using a similar approach so that it can be applied to any chocolatey install.

**Comment by mwrock** [comment]
Fixed by #68
