### ISSUE TITLE
Enhance Readme.md with example of private (secured) repository feed (or add feature if not possible)

### ISSUE THREAD

**Issue by DarwinJS** [chocolatey/chocolatey-cookbook#72]
I can't tell by the code if using a secured repo feed (secured for read access) is possible?

Do you have to register the source with the username and password - if so can this be done by the chocolatey cookbook?

Is it possible to provide a username and password on individual resource items (preferable).

Thanks.

**Comment by jedugas** [comment]
Darwin, look at this from the repo's examples...this has been demonstrated
to work with a private ProGet feed using user/passwordd authentication:

chocolatey "some_private_secure_package" do
  source "https://some.proget/feed"
  options ({'u' => 'username', 'p' => 'password'})end


On Tue, Dec 29, 2015 at 3:50 PM, Darwin <notifications@github.com> wrote:

> I can't tell by the code if using a secured repo feed (secured for read
> access) is possible?
>
> Do you have to register the source with the username and password - if so
> can this be done by the chocolatey cookbook?
>
> Is it possible to provide a username and password on individual resource
> items (preferable).
>
> Thanks.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/chocolatey/chocolatey-cookbook/issues/72>.
>



-- 
Jeff Dugas
*work*: jeffrey.dugas@clearesult.com
*mobile*: 508-244-7714
*skype*: jeffrey.dugas

**Comment by DarwinJS** [comment]
Excellent! Sorry I missed that.
