### ISSUE TITLE
Better way to pass arguments (args and params) to chocolatey?

### ISSUE THREAD

**Issue by docwhat** [chocolatey/chocolatey-cookbook#75]
Right now, there is `args` and `options` for passing in arguments to `cinst`/`chocolatey` but it can be confusing due to the layers of quoting that must be done:
1. Ruby
2. Powershell or CMD (I don't recall which)
3. [Chocolatey](https://github.com/chocolatey/choco/wiki/CommandsReference#how-to-pass-options--switches)

In addition, the `options` prepends a dash (`-`) to each argument, which makes doing double dash `--` items hard.

It took me a while to figure out how to pass in an `-ia` option with spaces in it.

A better solution might be passing in a `Hash` as an attribute of the resource and the cookbook would unpack that and do quoting on its own.  Or have it write an `.xml`, `.yml`, or `.json` file that Chocolatey could be made to understand.

Possible Example:

```
chocolatey 'VisualStudio2013Professional' do
  options(
    install_aguments: [ '/Silent', '/Features:WebTools Win8SDK'],
    debug: true,
    verbose: true,
    version: '12.0.21005.20141031'
  )
end
```

Alternatively, we could try to understand all possible options to chocolatey, but that seems like we'd be playing catch-up with Chocolatey all the time.  Example:

```
chocolatey 'VisualStudio2013Professional' do
  install_aguments [ '/Silent', '/Features:WebTools Win8SDK'],
  debug true,
  verbose true,
  version '12.0.21005.20141031'
end
```

**Comment by ferventcoder** [comment]
Thanks! I think @mwrock may have some answers for you on this.

**Comment by mwrock** [comment]
I don't think we want to map new attributes to chocolatey args for the same reasons you stated, but a hash that gets serialized to a list of chocolatey arguments sounds interesting.

**Comment by pauldambra** [comment]
I think this is the right place to ask (apologies if not)

I'm trying to

1:  include_recipe "chocolatey"
2:
3:  chocolatey "microsoft-build-tools"  do
4>>   options "--ignore-package-exit-codes"
5:  end  6:

Since ms-build-tools is returning exit code 3010 soft reboot and I don't want chef to exit

but I'm getting

> Chef::Exceptions::ValidationFailed: Option options must be a kind of Hash!

Can I pass in that argument?

Thanks
