### ISSUE TITLE
Support for Choco -Force

### ISSUE THREAD

**Issue by DarwinJS** [chocolatey/chocolatey-cookbook#76]
I would like to be able to check specific resources that a package has installed - say it's COM registration keys - and if they are missing, then re-run the relevant chocolatey package.

I tried passing -force like this:

    options ({'u' => 'user', 'p' => 'password', 'force' => ''})

But if I am understanding the provider code correctly the provider is doing it's own package existence check and so does not start chocolatey if the package is present.

Could -force be supported or allow chocolatey to do the check for whether a package is installed?

Also - if anyone has work around code that simply executes chocolatey, that would be helpful for the meantime.

**Comment by DarwinJS** [comment]
I figured out the work around code:

    execute 'install_googlechrome' do
      command 'choco install install_googlechrome -force -confirm -source https://custom.com/nuget/wwchoco -u user -p password'
      not_if {(::File.directory?('C:\Program Files (x86)\Google\Chrome\Application\chrome.exe') && registry_value_exists?('HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Wow6432Node\CLSID\{4AE7BB5D-6134-46FB-875A-9AFF2C6CF26C}\InprocServer32', { name: '', type: :string, data: 'somechromedll'}))}
    end

**Comment by mwrock** [comment]
assuming I can close. Please feel free to reopen if there is still an issue here.

**Comment by DarwinJS** [comment]
I guess I'm taken care of - making force natively supported might make future users of the chocolatey cookbook able to implement this more easily.

Fyi - It is also helpful for custom chocolatey packages where I do the idempotence internal to the package and want to always run with force.

**Comment by mwrock** [comment]
The next version of chef client will have a chocolatey package provider built in! So focus on usability improvements will shift over there but this cookbook will continue to be used for actually installing chocolatey and as a resource for current versions of chef.

**Comment by DarwinJS** [comment]
That's great to hear!  So I'd be interested in the giving the feedback for the new improved built-in chocolatey provider that "the package provider do it's own idempotence (if it has this built in) and supporting -force" so that I can do the self-healing scenarios like the above code.  If letting the underlying provider do it's own idempotence is not a good idea for some reason, at supporting and passing through -force.  Would be great if this was supported at the "package" level (https://docs.chef.io/resource_package.html) and inherited by all package provider types.  If that could be supported - then maybe down the road it would make sense for package providers to be able to receive an array of file system and registry references to check for existence, and if missing - reinstall the package.  (-force in the case of chocolatey, maybe some package providers support a reinstall command directly, some may need to uninstall and reinstall in order to accomplish a -force).

**Comment by mwrock** [comment]
Yeah the chef core package resource which will be gaining a new chocolatey provider does have its own idempotence check. I'd definitely encourage you to file an issue on the chef repo adding a force attribute to skip or override that.
