### ISSUE TITLE
What do you do when chocolatey.org is down? 

### ISSUE THREAD

**Issue by spuder** [chocolatey/chocolatey-cookbook#80]
If you depend on the chocolatey cookbook, your cookbook will break when chocolatey.org is down. 

<img width="532" alt="screenshot 2016-03-03 11 47 39" src="https://cloud.githubusercontent.com/assets/242382/13505285/c19f221a-e135-11e5-8bd7-459d1f12d413.png">

```ruby
Recipe: chocolatey::default
  * remote_file[c:\chef\local-mode-cache\cache/install.ps1] action create[2016-03-03T13:44:14-05:00] WARN: remote_file[c:\chef\local-mode-cache\cache/install.ps1] cannot be downloaded from https://chocolatey.org/install.ps1: 503 "Service Unavailable"


    ================================================================================
    Error executing action `create` on resource 'remote_file[c:\chef\local-mode-cache\cache/install.ps1]'
    ================================================================================

    Net::HTTPFatalError
    -------------------
    503 "Service Unavailable"

    Resource Declaration:
    ---------------------
    # In c:/chef/local-mode-cache/cache/cookbooks/chocolatey/recipes/default.rb

     29: remote_file install_ps1 do
     30:   source node['chocolatey']['url']
     31:   backup false
     32:   notifies :run, 'powershell_script[Install Chocolatey]', :immediately
     33:   not_if { chocolatey_installed? && (node['chocolatey']['upgrade'] == false) }
     34: end
     35:

    Compiled Resource:
    ------------------
    # Declared in c:/chef/local-mode-cache/cache/cookbooks/chocolatey/recipes/default.rb:29:in `from_file'

    remote_file("c:\chef\local-mode-cache\cache/install.ps1") do
      provider Chef::Provider::RemoteFile
      action [:create]
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      source ["https://chocolatey.org/install.ps1"]
      use_etag true
      use_last_modified true
      declared_type :remote_file
      cookbook_name "chocolatey"
      recipe_name "default"
      is_chocolatey_installed true
      atomic_update true
      path "c:\\chef\\local-mode-cache\\cache/install.ps1"
      not_if { #code block }
    end

```

## Possible solutions

1. Don't try and download the install.ps1 script every time chef runs. 

2. Document that users should mirror their own version of install.ps1 in an artifact repository.

3. Persuade chocolatey.org owners to put this file on an externally hosted mirror. (The [remote_file resource will take an array of locations](https://docs.chef.io/resource_remote_file.html), and attempt to download from them in order)

     source 'http://seapower/spring.png', 'http://seapower/has_sprung.png'

**Comment by ferventcoder** [comment]
actually, there is another option - see https://github.com/chocolatey/puppet-chocolatey/blob/master/templates/InstallChocolatey.ps1.erb

**Comment by ferventcoder** [comment]
Just include the ps1 locally in the cookbook. That is what the Puppet one does. And it ensures that companies using Chocolatey completely internally never suffer downtime based on the dot org site and the community packages repository going down for a little while for unplanned maintenance.

**Comment by ferventcoder** [comment]
https://twitter.com/chocolateynuget/status/705464268188024833

**Comment by ferventcoder** [comment]
@mwrock thoughts to doing similar to what the Puppet module does?

**Comment by ferventcoder** [comment]
And it's actually an edited one to point to local chocolatey resources so there is no call out to the site.

**Comment by mwrock** [comment]
Yeah I think thats a great idea @ferventcoder. I'll add soon.
