### ISSUE TITLE
'choco' env variable not set when installed in same chef run

### ISSUE THREAD

**Issue by joemillerr** [chocolatey/chocolatey-cookbook#87]
It seems I cannot use chocolatey to install packages in the same Chef run as I install chocolatey.  When bootstrapping a new machine and installing chocolatey via the default recipe, the 'choco' isn't recognized yet.  This seems like something you should be able to do but I don't know what the best way to achieve it is.

```
Mixlib::ShellOut::ShellCommandFailed
------------------------------------
Expected process to exit with [0], but received '1'
---- Begin output of choco list --localonly ----
STDOUT: 
STDERR: 'choco' is not recognized as an internal or external command,
operable program or batch file.
---- End output of choco list --localonly ----
Ran choco list --localonly returned 1
```

**Comment by ferventcoder** [comment]
@mwrock this is something we handle with Puppet - seems like there is a way to get it to work with Chef as well.

**Comment by mwrock** [comment]
We have actually handled this for quite some time. Its possible that choco was never in fact installed. @joemillerr did you include the default recipe of this cookbook in your runlist? Thats what actually installs choco on a node. Also if you are using a recent version of the chef client, you can use its built in `chocolatey_package` resource and it will detect when choco is missing and recommend using the default recipe of this cookbook.

**Comment by joemillerr** [comment]
Hey @mwrock sorry for the delayed response, I didn't get notified for whatever reason. 

I am in fact including the default recipe for chocolatey before I'm attempting to use chocolatey and then I am using the chocolatey_package resource.  Its also important to note if I run chef-client for a second time I don't get this error again.  I'm on chef-client version 12.9.38.  Thanks for your help!

**Comment by mwrock** [comment]
so this is very strange. Based on your error above `shellout` is being called with `choco list --localonly` but we don't do that in the chocolatey resource even checking the source from v12.9.38. We call `choco.exe` using the absolute path and we call `list -l -r` for grabbing the local list.

Even this cookbook also calls the absolute path but if you are using `chocolatey_package` that should be calling into the core chef resource.

Is it at all possible you are using another command resource somewhere to call chocolatey?

**Comment by joemillerr** [comment]
I went back through everything and I'm including recipe 'chocolatey', using chocolatey_package everywhere else, and confirmed v1.0.0 of the chocolatey cookbook.  Definitely an odd issue, I need to test this on a few new machines.  Thanks for the help @mwrock !

**Comment by mwrock** [comment]
could you run with `-l debug` which should produce a full stack trace to help pinpoint the source.

**Comment by joemillerr** [comment]
Yea, there has to be something buried somewhere.
