### ISSUE TITLE
 NoMethodError  undefined method `new' for Chocolatey:Module

### ISSUE THREAD

**Issue by ajkumarnv** [chocolatey/chocolatey-cookbook#95]
Recipe: mrts_choco::default
  * directory[C:/ProgramData/chocolatey//config] action create (up to date)
  * cookbook_file[chocolatey.config] action create (up to date)
  * chocolatey[pyyaml] action install

    ============================================================================
====
    Error executing action `install` on resource 'chocolatey[pyyaml]'
    ============================================================================
====

    NoMethodError
    -------------
    undefined method `new' for Chocolatey:Module

    Resource Declaration:
    ---------------------

**Comment by mwrock** [comment]
can we get a stacktrace running with `-l debug`? Thanks!

**Comment by ajkumarnv** [comment]
[chef-client-logs.txt](https://github.com/chocolatey/chocolatey-cookbook/files/388762/chef-client-logs.txt)

Log file is attached.

My chef client version is 12.0.3.

Issue is automatically resolved if i upgrade to chef client version 12.12.15

**Comment by mwrock** [comment]
closing here since the resource erroring is the chef core resource and not the one in this cookbook.

**Comment by HighwayofLife** [comment]
I'm getting this error as well with Chef Client, version 13.0.118

While running with kitchen:
```
undefined method `new' for Chocolatey:Module
```
Log file attached.
[default-Windows2016.log.txt](https://github.com/chocolatey/chocolatey-cookbook/files/976746/default-Windows2016.log.txt)

**Comment by mwrock** [comment]
Are you using the `chocolatey` resource from this cookbook? On chef 13, use the [`chocolatey_package`])(https://docs.chef.io/resource_chocolatey_package.html) resource instead:

**Comment by HighwayofLife** [comment]
@mwrock Thanks, that was the case. I caught that bit in the readme yesterday. It's working now with `chocolatey_package` resource.
