### ISSUE TITLE
Setting chocolateyVersion doesn't seem to be picked up

### ISSUE THREAD

**Issue by emachnic** [chocolatey/chocolatey-cookbook#97]
It seems that setting `node['chocolatey']['install_vars']['chocolateyVersion']` isn't being picked up properly by the installation. I've tried setting this in my attributes file and in the actual recipe of my wrapper cookbook. I'm wondering if this has to do with the way environment variable work (or don't work) on Windows in that running the installation without starting a new session does not pick up the set env variable.

To reproduce, from a wrapper cookbook, set `node.default['chocolatey']['install_vars']['chocolateyVersion'] = '0.9.10.3'` and then include the `chocolatey` recipe. The expected outcome should be that version 0.9.10.3 of Chocolatey is installed but the actual is that 0.10.0 is installed.

Any ideas what's happening and how I can make sure that 0.9 is the installed version since 0.10 introduced breaking changes that many Chocolatey packages have not adjusted for.

**Comment by ferventcoder** [comment]
> Any ideas what's happening and how I can make sure that 0.9 is the installed version since 0.10 introduced breaking changes that many Chocolatey packages have not adjusted for.

Adjusting your terminology a bit: "Introduced a breaking change (security enhancement) that many Chocolatey packages *on the community repository* have not *yet* adjusted for."

Also more detail into the reasoning why and why now at https://github.com/chocolatey/choco/blob/master/CHANGELOG.md#0100-august-11-2016

**Comment by emachnic** [comment]
@ferventcoder I have no problem with the change. Unfortunately it's causing issues, with the "consul" package for one, as that doesn't have a checksum for the installation.

**Comment by ferventcoder** [comment]
@emachnic I'm not seeing that - consul itself is all included, so no need for checksums - https://chocolatey.org/packages/consul

Could be the dependent package, nssm. https://chocolatey.org/packages/NSSM

**Comment by ferventcoder** [comment]
Yes, looks like NSSM.

**Comment by ferventcoder** [comment]
You can also add install options to allow the package to ignore checksums.

**Comment by emachnic** [comment]
@ferventcoder is the the `args` option to the `chocolatey` resource or `options`?

**Comment by ferventcoder** [comment]
I know @mwrock can give you exact arguments, I'm less familiar.

**Comment by ferventcoder** [comment]
This is still possibly a bug by the way.

**Comment by emachnic** [comment]
@ferventcoder Yeah, I'm honestly not sure where the issue actually lies though I want to say it's Windows' env var handling. At this point, I'm looking more for a way around this.

**Comment by mwrock** [comment]
Yeah looking over this it absolutely looks like a bug. The attribute is never emmited to the environment or a template variable it is just swallowed. I'll make sure that gets fixed today or this weekend.

@emachnic you can pass options to choco via the `options` property and that usage varies slightly depending on if you are using the resource in this cookbook or the `chocolatey` resource in core chef.

This cookbook:
`options { '-allowemptychecksum' =>nil }`

Chef:
`options `--allowemptychecksum'`

**Comment by emachnic** [comment]
@mwrock The `options ({ '-allowemptychecksum' => nil })` seems to work. Can I ask as it isn't totally clear in the README, what the difference is between the args and the options?

**Comment by mwrock** [comment]
yeah that does seem very confusing. `args` is a "convenience" property and its value is passed to the choco `-ia` flag. I'd just remove it if it didn't break people but could use better docs. Going forward, I recommend folks to only use this cookbook to actually install choco and use core chef's `chocolatey` resource if you can use a recent version of chef.

**Comment by emachnic** [comment]
That's actually the idea I was thinking after seeing the resource docs.
Maybe you should have just an install recipe that doesn't include the
resource?

**Comment by mwrock** [comment]
We still want to support earlier versions of chef 12 and chef 11.

**Comment by mwrock** [comment]
The fix is now released in 1.0.2.
