### ISSUE TITLE
Choco not ChefSpec friendly?

### ISSUE THREAD

**Issue by dhoer** [chocolatey/chocolatey-cookbook#98]
I'm trying to update ghostdriver cookbook that depends on phantomjs that depends on chocolatey for windows. I use mixlib in my cookbook and can't for the life of me figure out how to get around these types of errors below in chefspec.  Is there chefspec examples out there that use chocolatey cookbook?   I have mocked out the mixlib, but that doesn't seem to work.

e.g.,
```
  #   let(:shellout) do
  #     double(run_command: nil, error!: nil, error?: false, stdout: '1',
  #            stderr: double(empty?: true), exitstatus: 0,
  #            :live_stream= => double)
  #   end
  #
  #   before do
  #     stub_command('netsh advfirewall firewall show rule name="ghostdriver_standalone" > nul')
  #     allow(Mixlib::ShellOut).to receive(:new).and_return(shellout)
  #     allow_any_instance_of(Mixlib::ShellOut).to receive(:new).and_return(shellout)
  #   end
  #
  #   include Chef::Mixin::PowershellOut
```

    Failure/Error:
       ChefSpec::SoloRunner.new(
         platform: 'windows', version: '2008R2', step_into: ['ghostdriver']
       ).converge(described_recipe)

       ghostdriver[ghostdriver_standalone] (ghostdriver_test::standalone line 1) had an error: RSpec::Mocks::MockExpectationError: #<Double (anonymous)> received unexpected message :live_stream with (no args)
     # /Users/hoerde/.rvm/gems/ruby-2.3.0/gems/chef-12.13.37/lib/chef/mixin/shell_out.rb:85:in `shell_out_command'
     # /Users/hoerde/.rvm/gems/ruby-2.3.0/gems/chef-12.13.37/lib/chef/mixin/shell_out.rb:39:in `shell_out'
     # /Users/hoerde/.rvm/gems/ruby-2.3.0/gems/chef-12.13.37/lib/chef/mixin/powershell_out.rb:67:in `block in run_command_with_os_architecture'
     # /Users/hoerde/.rvm/gems/ruby-2.3.0/gems/chef-12.13.37/lib/chef/mixin/windows_architecture_helper.rb:67:in `with_os_architecture'
     # /Users/hoerde/.rvm/gems/ruby-2.3.0/gems/chef-12.13.37/lib/chef/mixin/powershell_out.rb:66:in `run_command_with_os_architecture'
     # /Users/hoerde/.rvm/gems/ruby-2.3.0/gems/chef-12.13.37/lib/chef/mixin/powershell_out.rb:37:in `powershell_out'
     # /Users/hoerde/.rvm/gems/ruby-2.3.0/gems/chef-12.13.37/lib/chef/mixin/powershell_out.rb:47:in `powershell_out!'
     # /var/folders/kl/1m4f0gbd62b7wgqb1tt6cg180000gn/T/d20160826-51637-qmes3r/cookbooks/chocolatey/libraries/helpers.rb:49:in `env_var'
     # /var/folders/kl/1m4f0gbd62b7wgqb1tt6cg180000gn/T/d20160826-51637-qmes3r/cookbooks/chocolatey/libraries/helpers.rb:45:in `machine_env_var'
     # /var/folders/kl/1m4f0gbd62b7wgqb1tt6cg180000gn/T/d20160826-51637-qmes3r/cookbooks/chocolatey/libraries/helpers.rb:9:in `block in chocolatey_install'
     # /var/folders/kl/1m4f0gbd62b7wgqb1tt6cg180000gn/T/d20160826-51637-qmes3r/cookbooks/chocolatey/libraries/helpers.rb:9:in `fetch'
     # /var/folders/kl/1m4f0gbd62b7wgqb1tt6cg180000gn/T/d20160826-51637-qmes3r/cookbooks/chocolatey/libraries/helpers.rb:9:in `chocolatey_install'
     # /var/folders/kl/1m4f0gbd62b7wgqb1tt6cg180000gn/T/d20160826-51637-qmes3r/cookbooks/chocolatey/libraries/helpers.rb:26:in `chocolatey_installed?'
     # /var/folders/kl/1m4f0gbd62b7wgqb1tt6cg180000gn/T/d20160826-51637-qmes3r/cookbooks/chocolatey/recipes/default.rb:40:in `block (2 levels) in from_file'
     # /Users/hoerde/.rvm/gems/ruby-2.3.0/gems/chef-12.13.37/lib/chef/resource/conditional.rb:106:in `evaluate_block'
     # /Users/hoerde/.rvm/gems/ruby-2.3.0/gems/chef-12.13.37/lib/chef/resource/conditional.rb:95:in `evaluate'
     # /Users/hoerde/.rvm/gems/ruby-2.3.0/gems/chef-12.13.37/lib/chef/resource/conditional.rb:88:in `continue?'
     # /Users/hoerde/.rvm/gems/ruby-2.3.0/gems/chef-12.13.37/lib/chef/resource.rb:1507:in `block in should_skip?'
     # /Users/hoerde/.rvm/gems/ruby-2.3.0/gems/chef-12.13.37/lib/chef/resource.rb:1506:in `each'
     # /Users/hoerde/.rvm/gems/ruby-2.3.0/gems/chef-12.13.37/lib/chef/resource.rb:1506:in `find'
     # /Users/hoerde/.rvm/gems/ruby-2.3.0/gems/chef-12.13.37/lib/chef/resource.rb:1506:in `should_skip?'
     # /Users/hoerde/.rvm/gems/ruby-2.3.0/gems/chefspec-5.0.0/lib/chefspec/extensions/chef/resource.rb:19:in `run_action'
     # /Users/hoerde/.rvm/gems/ruby-2.3.0/gems/chef-12.13.37/lib/chef/runner.rb:69:in `run_action'
     # /Users/hoerde/.rvm/gems/ruby-2.3.0/gems/chef-12.13.37/lib/chef/runner.rb:97:in `block (2 levels) in converge'
     # /Users/hoerde/.rvm/gems/ruby-2.3.0/gems/chef-12.13.37/lib/chef/runner.rb:97:in `each'
     # /Users/hoerde/.rvm/gems/ruby-2.3.0/gems/chef-12.13.37/lib/chef/runner.rb:97:in `block in converge'
     # /Users/hoerde/.rvm/gems/ruby-2.3.0/gems/chef-12.13.37/lib/chef/resource_collection/resource_list.rb:94:in `block in execute_each_resource'
     # /Users/hoerde/.rvm/gems/ruby-2.3.0/gems/chef-12.13.37/lib/chef/resource_collection/stepable_iterator.rb:116:in `call_iterator_block'
     # /Users/hoerde/.rvm/gems/ruby-2.3.0/gems/chef-12.13.37/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
     # /Users/hoerde/.rvm/gems/ruby-2.3.0/gems/chef-12.13.37/lib/chef/resource_collection/stepable_iterator.rb:104:in `iterate'
     # /Users/hoerde/.rvm/gems/ruby-2.3.0/gems/chef-12.13.37/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
     # /Users/hoerde/.rvm/gems/ruby-2.3.0/gems/chef-12.13.37/lib/chef/resource_collection/resource_list.rb:92:in `execute_each_resource'
     # /Users/hoerde/.rvm/gems/ruby-2.3.0/gems/chef-12.13.37/lib/chef/runner.rb:96:in `converge'
     # /Users/hoerde/.rvm/gems/ruby-2.3.0/gems/chef-12.13.37/lib/chef/provider.rb:417:in `block in recipe_eval'
     # /Users/hoerde/.rvm/gems/ruby-2.3.0/gems/chef-12.13.37/lib/chef/mixin/why_run.rb:52:in `add_action'
     # /Users/hoerde/.rvm/gems/ruby-2.3.0/gems/chef-12.13.37/lib/chef/provider.rb:176:in `converge_by'
     # /Users/hoerde/.rvm/gems/ruby-2.3.0/gems/chef-12.13.37/lib/chef/provider.rb:412:in `recipe_eval'
     # /var/folders/kl/1m4f0gbd62b7wgqb1tt6cg180000gn/T/d20160826-51637-qmes3r/cookbooks/ghostdriver/providers/default.rb:25:in `block in class_from_file'
     # /Users/hoerde/.rvm/gems/ruby-2.3.0/gems/chef-12.13.37/lib/chef/provider.rb:145:in `run_action'
     # /Users/hoerde/.rvm/gems/ruby-2.3.0/gems/chef-12.13.37/lib/chef/resource.rb:603:in `run_action'
     # /Users/hoerde/.rvm/gems/ruby-2.3.0/gems/chefspec-5.0.0/lib/chefspec/extensions/chef/resource.rb:22:in `run_action'
     # /Users/hoerde/.rvm/gems/ruby-2.3.0/gems/chef-12.13.37/lib/chef/runner.rb:69:in `run_action'
     # /Users/hoerde/.rvm/gems/ruby-2.3.0/gems/chef-12.13.37/lib/chef/runner.rb:97:in `block (2 levels) in converge'
     # /Users/hoerde/.rvm/gems/ruby-2.3.0/gems/chef-12.13.37/lib/chef/runner.rb:97:in `each'
     # /Users/hoerde/.rvm/gems/ruby-2.3.0/gems/chef-12.13.37/lib/chef/runner.rb:97:in `block in converge'
     # /Users/hoerde/.rvm/gems/ruby-2.3.0/gems/chef-12.13.37/lib/chef/resource_collection/resource_list.rb:94:in `block in execute_each_resource'
     # /Users/hoerde/.rvm/gems/ruby-2.3.0/gems/chef-12.13.37/lib/chef/resource_collection/stepable_iterator.rb:116:in `call_iterator_block'
     # /Users/hoerde/.rvm/gems/ruby-2.3.0/gems/chef-12.13.37/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
     # /Users/hoerde/.rvm/gems/ruby-2.3.0/gems/chef-12.13.37/lib/chef/resource_collection/stepable_iterator.rb:104:in `iterate'
     # /Users/hoerde/.rvm/gems/ruby-2.3.0/gems/chef-12.13.37/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
     # /Users/hoerde/.rvm/gems/ruby-2.3.0/gems/chef-12.13.37/lib/chef/resource_collection/resource_list.rb:92:in `execute_each_resource'
     # /Users/hoerde/.rvm/gems/ruby-2.3.0/gems/chef-12.13.37/lib/chef/runner.rb:96:in `converge'
     # /Users/hoerde/.rvm/gems/ruby-2.3.0/gems/chef-12.13.37/lib/chef/client.rb:669:in `block in converge'
     # /Users/hoerde/.rvm/gems/ruby-2.3.0/gems/chef-12.13.37/lib/chef/client.rb:664:in `catch'
     # /Users/hoerde/.rvm/gems/ruby-2.3.0/gems/chef-12.13.37/lib/chef/client.rb:664:in `converge'
     # /Users/hoerde/.rvm/gems/ruby-2.3.0/gems/chefspec-5.0.0/lib/chefspec/solo_runner.rb:127:in `converge'
     # ./spec/unit/standalone_spec.rb:8:in `block (3 levels) in <top (required)>'
     # ./spec/unit/standalone_spec.rb:51:in `block (3 levels) in <top (required)>'
     # ------------------
     # --- Caused by: ---
     #   #<Double (anonymous)> received unexpected message :live_stream with (no args)
     #   /Users/hoerde/.rvm/gems/ruby-2.3.0/gems/chef-12.13.37/lib/chef/mixin/shell_out.rb:85:in `shell_out_command'

**Comment by mwrock** [comment]
I would avoid:
```
allow(Mixlib::ShellOut).to receive(:new).and_return(shellout)
```
and always try to include a `.with` specifying the command you intend to mock (or atleast a regex) so that you only mock the shellout instances you control.

**Comment by dhoer** [comment]
Awesome! That worked like a charm.  Thanks
